### ISSUE TITLE
It's not work in windows 10 pc

### ISSUE THREAD

**Issue by dazhaxie** [simbleau/vong#1]
![image](https://github.com/simbleau/vong/assets/2949696/341aa165-d5bf-4f5d-b04b-c5a395cdad3d)

**Comment by nuzzles** [comment]
Hey, do you have an error or anything I can work with?

I assume the demo on the blog in chrome works?

https://simbleau.github.io/rust/graphics/2023/11/20/using-vello-for-video-games.html

**Comment by nuzzles** [comment]
@dazhaxie any update?
