### ISSUE TITLE
How to render the Canvas

### ISSUE THREAD

**Issue by zhuoqinyue** [simbleau/vong#2]
Great Project !

I have some questions: 
1. What crate did you use to render this project into Canvas?
2. How to monitor key presses on the keyboard？Are there any crates here that can monitor the keyboard?

**Comment by nuzzles** [comment]
`bevy` has a render pipeline and input handling through `winit` under the hood.
 
`bevy-vello` is used under the hood, which renders to the canvas[ using this shader.](https://github.com/vectorgameexperts/bevy-vello/blob/main/shaders/vello_ss_rendertarget.wgsl)

https://simbleau.github.io/rust/graphics/2023/11/20/using-vello-for-video-games.html may have more details.

**Comment by zhuoqinyue** [comment]
And one more question: 
Why can’t I press `F12` to bring up the console on this [website](https://simbleau.github.io/vong/)? Is this an Easter egg?

**Comment by nuzzles** [comment]
No. There is nothing purposefully preventing you from bringing up the console.

Open the developer tools before you navigate to the link. :)
